# Generated by Django 4.0.3 on 2022-09-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_automobilevo_import_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
